Repository codebuddies/cb-connect, pull requests merged in 2019-04, with the labels that each got.

#47 fixes #46
  imports/ui/components/apply.jsx
Labels: [state] in-review

#55 Setup TravisCI
  .travis.yml
Labels: [state] in-progress, [tech] infrastructure, [type] enhancement

#62 Update NPM dependencies
  package-lock.json
  package.json
Labels: [state] in-review, [tech] infrastructure, [type] enhancement

#64 Update Travis build actions
  .travis.yml
  package.json
Labels: [tech] infrastructure

#53 WIP: let users flag entries
  .eslintrc.json
  imports/api/entries/entries.js
  imports/api/entries/server/helpers.js
  imports/ui/components/dashboard/dashboard.jsx
  imports/ui/components/dashboard/dashboard_cards_section.jsx
  imports/ui/components/dashboard/dashboard_sidebar.jsx
  imports/ui/components/dashboard/match_card.jsx
  imports/ui/components/dashboard/matches_section.jsx
  imports/ui/components/hoc/AuthProvider.jsx
  imports/ui/components/hoc/AuthenticatedRoute.jsx
  imports/ui/components/moderator.jsx
  package-lock.json
  server/users/methods.js
Labels: [state] in-progress, [tech] javascript, [tech] meteorjs, [tech] react, [type] feature
